<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MCmodsLoader.Core\MCmodsLoader.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MCmodsLoader</AssemblyName>
    <AssemblyTitle>MCmodsLoader</AssemblyTitle>
    <Product>MCmodsLoader</Product>
    <Description>Zero-Setup Performance Injector for the Vanilla Launcher</Description>
    <Authors>SecretLUL</Authors>
  </PropertyGroup>

</Project>
